# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-10 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
